---
- name: update apt cache
  apt: update_cache=yes cache_valid_time=7200

- name: update all packages
  apt: upgrade=full
  when: update_packages is defined

- name: install systemd
  apt: name=systemd state=present

- name: enable systemd
  copy: src=cmdline.txt dest=/boot/cmdline.txt owner=root group=root mode=755

- name: install needed packages
  apt: name={{ item }} state=present
  with_items:
  - vim
  - tmux
  - python-setuptools
  - python-yaml
  - python-requests

- name: remove unneeded stuff
  apt: name={{ item }} state=absent purge=yes
  with_items:
  - desktop-base
  - gnome*
  - lightdm
  - lx*
  - obconf
  - openbox
  - raspberrypi-artwork
  - wolfram-engine
  - x11*
  - xarchiver
  - xinit
  - xserver*
  - leafpad
  - smartsim
  - gpicview
  - galculator
  - "*minecraft*"
  - penguinspuzzle
  - omxplayer
