---
# base image is Raspbian Jessie (8) Lite - https://www.raspberrypi.org/downloads/raspbian/

- name: update apt cache
  apt: update_cache=yes cache_valid_time=7200

- name: update all packages
  apt: upgrade=full
  when: update_packages is defined

- name: install needed packages
  apt: name={{ item }} state=present
  with_items:
  - git
  - vim
  - tmux
  - python-setuptools
  - python-yaml
  - python-requests

#- name: remove unneeded stuff
#  apt: name={{ item }} state=absent purge=yes
#  with_items:
#  - triggerhappy

- name: set timezone
  command: timedatectl set-timezone {{ timezone }}
  when: timezone is defined

- name: enable i2c and watchdog
  lineinfile:
    dest: /boot/config.txt
    regexp: "^dtparam={{ item.key }}="
    line: "dtparam={{ item.key }}={{ item.val }}"
  with_items:
  - key: i2c_arm
    val: "on"
  - key: watchdog
    val: "on"
  register: dtparams

- pause: prompt="Device tree configuration changed - reboot recommended"
  when: dtparams.changed

#TODO: resize partition
