---
- name: system setup
  hosts: all
  sudo: true
  vars:
    timezone: Europe/Vienna
  roles:
  - system_setup
  tags:
  - system_setup

- name: deploy git repo
  hosts: all
  roles:
  - { role: deploy_growd, local_git_dir: "..", repo_name: growd }

- name: install growd
  hosts: all
  sudo: true
  sudo_user: root
  roles:
  - { role: install_growd, repo_path: "/home/pi/growd" }

- name: install ssh tunnel
  hosts: all
  sudo: true
  sudo_user: root
  roles:
  - role: ssh_portfwd
    when: setup_portfwd is defined and setup_portfwd == true
