---
#TODO: uninstall?

- name: install python package for development
  command: python setup.py develop
  args:
    chdir: "{{ repo_path }}"

- name: copy configuration file
  copy:
    src: "{{ config_file }}"
    dest: /etc/growd.yml
    backup: yes
  when: config_file is defined
  notify: restart growd

- name: copy systemd service file
  copy:
    src: "{{ repo_path }}/init/growd.service"
    dest: /etc/systemd/system/growd.service
    remote_src: true
  notify: systemctl daemon-reload

- name: enable and start service
  service:
    name: growd
    state: started
    enabled: yes

- name: link /usr/local/bin/growd-main to /usr/bin
  file:
    src: /usr/local/bin/growd-main
    dest: /usr/bin/growd-main
    state: link
